version: '3'

services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    depends_on:
      - model-service
      - mcp-service
      - conversation-service
      - db-service

  model-service:
    build:
      context: ./services/model-service
      dockerfile: Dockerfile.dev
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/model-service:/app
      - /app/node_modules

  mcp-service:
    build:
      context: ./services/mcp-service
      dockerfile: Dockerfile.dev
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/mcp-service:/app
      - /app/node_modules
    depends_on:
      - db-service

  conversation-service:
    build:
      context: ./services/conversation-service
      dockerfile: Dockerfile.dev
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/conversation-service:/app
      - /app/node_modules
    depends_on:
      - db-service

  db-service:
    build:
      context: ./services/db-service
      dockerfile: Dockerfile.dev
    ports:
      - "4004:4004"
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/db-service:/app
      - /app/node_modules
      - db-data:/app/data

volumes:
  db-data:
