version: '3'

services:
  web:
    build:
      context: ./apps/web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - model-service
      - mcp-service
      - conversation-service
      - db-service

  model-service:
    build:
      context: ./services/model-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  mcp-service:
    build:
      context: ./services/mcp-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    depends_on:
      - db-service

  conversation-service:
    build:
      context: ./services/conversation-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
    depends_on:
      - db-service

  db-service:
    build:
      context: ./services/db-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
    volumes:
      - db-data:/app/data

volumes:
  db-data:
