version: '3'

services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - model-service
      - mcp-service
      - conversation-service
      - db-service

  model-service:
    build:
      context: ./services/model-service
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production

  mcp-service:
    build:
      context: ./services/mcp-service
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
    depends_on:
      - db-service

  conversation-service:
    build:
      context: ./services/conversation-service
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=production
    depends_on:
      - db-service

  db-service:
    build:
      context: ./services/db-service
      dockerfile: Dockerfile
    ports:
      - "4004:4004"
    environment:
      - NODE_ENV=production
    volumes:
      - db-data:/app/data

volumes:
  db-data:
